apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openquery.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openquery.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
