apiVersion: v1
kind: Service
metadata:
  name: {{ include "openquery.fullname" . }}-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "openquery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
